version: 1.0.0.{build}
branches:
  only:
  - master
  - dev
configuration: Release
init:
- git config --global core.autocrlf true
clone_folder: c:\projects\enjoycqrs
environment:
  COVERALLS_REPO_TOKEN:
    secure: k131M9lYqPhmepQEei/Q2U5Pz+PJ+PQ0Suz4s6PYE/E+Ssk+NAjqExcGOGqvtx/B
skip_commits:
  message: /updated readme.*/
platform: Any CPU
clone_depth: 1
artifacts:
- path: src
  name: src
before_build:
  - ps: . .\build.ps1 Prepare-Build
build_script:
  - ps: . .\build.ps1 Build-Only
after_build:
  - ps: . .\build.ps1 Pack-Nuget
test_script:
  - ps: . .\build.ps1 Test-Coverage
deploy:
- provider: NuGet
  api_key:
    secure: NAbtRfAbJ7QcwtGR75wAcofcV+ipa6tKWGP798krZRjOYParVolf71xX5JBy+rUR
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  server: https://www.myget.org/F/enjoy/api/v2/package
  api_key:
    secure: zPU3TMfMcbGiOTRpcKdNjztuCMOtjdBB0ReA9tkMCs9XKejC9NKMVvEGvz7HFmEP
  skip_symbols: true
  on:
    branch: dev